language: php
sudo: false
php:
- '5.6'
- '7.0'
- '7.1'
- '7.2'
script:
- echo 'Tested'
before_deploy:
      - git config --local user.name "artikus11"
      - git config --local user.email "artikus.sol@gmail.ru"
      - git tag "1.8.4"
deploy:
  provider: releases
  api_key:
    secure: FNRV0Ky/plviY6QnbvfuD2DuKt8Gje7LDeQIXg5buZocTUBchz9vN2TrNkIuhOQBG9NVE01NCfDhZsHmiQ1pGBXWiyNt6POxqPHTN5FoqUg+Jl5At5LrTZQumBHdT7GYu6PUPBCgT2gBQprJ/7NaGt3KKZ7B3OZufHtjKVSSg26KceBW/UVPkunuj0jrMgngZe/lhNkU29ZLwXBkz5lOF7OGPghNW+LLg+qVSsuPg9ydV/hbHJluYzm7AzCfj+AKSyoCh7CwIC6PubFJuUoMDrVP+yRQNTX7kttJQsrsb1uMu2fUoSaEyOICSyUyl0l8wQQb6tsjMxZXCg4GgNRj9llDuhs+Q/oWEfPf+6ahLeiVzIvE17njn6t2XYQaPOX5JiVPJD8u794Ow5oPfAfWzfRZj+WjQlm3a/u06j++TNyA2XsgDGKI/w+BEDwe+y7b8iQlEHUxfZIHQ9PdZf3fDh3Hj4hHrxxmjVrPHJWapz7rPDwtwvXfderUxzRybWqOTN4lrk3AT/zaslIkg8uqNFHN/LMEfcBvwnJz6LrHGnlULmvx3AAd9iIUZoEFMAa3C6Hid7QwRO23XuuhlWXD/JOdxEnOWJuH3dq9AME0oMWhTaYC8RG23CoiGuNyzYiIWrzkr3qBchDQtJzsqYeUcRFc99XI19uYgqPGwPPR70E=
  file: latest.zip
  on:
    php: 7.0
    repo: artikus11/art-woo-order-one-click
after_deploy: "release created"